{
  "comments": [
    {
      "key": {
        "uuid": "c930e271_d3799892",
        "filename": "src/client/linux/handler/exception_handler_unittest.cc",
        "patchSetId": 3
      },
      "lineNbr": 267,
      "author": {
        "id": 1001629
      },
      "writtenOn": "2018-01-31T20:32:34Z",
      "side": 1,
      "message": "here",
      "revId": "242327485dc3f7652c17faf1b3082186700bd9fe",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}